version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/apps/front
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
   - object: /home/ec2-user/apps/front
     owner: ec2-user
     group: ec2-user
     mode: 755
     
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root

