version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/apps/front
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
     
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user

