name: Deploy 

on:
  push:
    branches:
      - develop 

jobs: 
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v2

      - name: Check Node v 
        run: node -v

      - name: Install Dependencies 
        run: yarn install --frozen-lockfile

      - name: Build 
        run: yarn build
      - name: zip create 
        run: zip -qq -r ./build.zip .
        shell: bash

      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp --region ap-northeast-2 ./build.zip s3://moamoa1-bucket/build.zip

      - name: Deploy 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws deploy create-deployment
          --application-name Github-Actions-Deploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name Github-Actions-Group
          --s3-location bucket=moamoa1-bucket,key=build.zip,bundleType=zip
          --region ap-northeast-2
